### ISSUE TITLE
LPG: Clarifications of BOM etc 

### ISSUE THREAD

**Issue by RedactedCode** [diysynth/EURORACK-MODULES#1]
Thanks so much for creating this repo. 

The LPG looks like a great project for a *complete* electronics DIY beginner (like me), but maybe some clarifications & more detail in the BOM etc might help us all along.

I completely understand that you have other things to spend time on, and that you have created this repo for the benefit of others and to no (financial) profit for yourself, and please take this feedback as constructive wishes: it is definitely *not* intended as criticism or meant to express ingratitude!

- Comparing the list of components needed with the pics it seems a connector block for JP1 is missing. Is i t maybe an XH type? 
- (Perhaps which wires from the connector go to which points on the switch is left to the student as an exercise)
- "standard" as the description of the toggle switch is a bit broad. It probably means miniature but a beginner might be a bit confused when they look at all the different kinds available.
- Similarly with the capacitors, while we can pick up expected values from the schematic, perhaps it would be helpful to specify a common type that would fulfil the spec (e.g. if someone goes to eBay & searches for capacitors, they are presented with a wild number of possible types - ceramics, tantalums, foils, electrolytics & so on, all with varying pitches & other specs like "axial" or "radial")
- It would really help to also have jpg/png of the front & rear of the boards when they are fully populated before final assembly with the front panel.

**Comment by diysynth** [comment]
Sorry for the late answer. You are right, most of my modules are not completly beginner friendly. I will try to add more notes in future BOMs. Some clarification to the points you mentioned:

- JP1 doesn't need to be a connector. You can just use wire to connect the switch to the pcb
- PIN 2 of JP1 should be connected to the middle pin of the switch. PIN 1 & 3 can be connected to either of the left or right pins of the switch.
- It is a miniature type **ON-OFF-ON switch** (with the same footprint like the Marquardt 9040 for example)
- For eurorack it is always a good idea to use capacitors that can withstand a voltage of at least 25V. In my designs the type of capacitors doesn't really matter. The only things that really matters are the voltage rating and the tolerance, which should be under 10%. Foil or ceramic capacitors and electrolytic caps are usually the way to go.
- I can add better/more pictures for future modules.
